version: '3.1'
services:
  odoo:
    container_name: odoo-andromat
    #image: odoo:16.0
    build:
      context: ./docker/16.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - andromat_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  andromat_data:
  postgres_data: