{
    'name': 'ConOdoo Consultores - package dependencies',
    'category': 'Sales/CRM',
    'sequence': 150,
    'summary': 'Centralize dependencies installation',
    'description': "",
    'depends': [
        'disable_odoo_online',
        'mail_debrand',
        'mass_editing',
        'l10n_es',
        'l10n_es_partner',
        'l10n_es_toponyms',
        'remove_odoo_enterprise',
        'partner_contact_access_link',
        'web_advanced_search',
        'web_refresher',
        'web_no_bubble',
        'web_responsive',
        'web_tree_many2one_clickable'
    ],
    'data': [],
    'application': True,
    'license': 'LGPL-3',
}
